# Generated by Django 4.2.1 on 2023-06-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_subscription_subscription_unique_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_subscribed",
        ),
    ]
