# Generated by Django 4.2.1 on 2023-06-18 19:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_is_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[users.validators.check_login],
                verbose_name="Логин",
            ),
        ),
    ]
