# Generated by Django 4.2.1 on 2023-06-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredientamount",
            options={
                "ordering": ("recipe__name",),
                "verbose_name": "Ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецепте",
            },
        ),
    ]
