# Generated by Django 4.2.1 on 2023-06-22 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredientamount",
            name="amount",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Количество не может быть меньше 1"
                    )
                ],
                verbose_name="Количество",
            ),
        ),
    ]
