# Generated by Django 4.2.1 on 2023-06-25 14:53

from django.db import migrations, models
import django_extensions.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_recipeingredientamount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[django_extensions.validators.HexValidator(max_length=7)],
                verbose_name="Цвет в HEX",
            ),
        ),
    ]
